### ISSUE TITLE
(NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'bubblingEventTypes' of null | Getting in new architecture

### ISSUE THREAD

**Issue by Prajwaltechversant** [Shopify/flash-list#1352]
(NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'bubblingEventTypes' of null       

This error is located at:
    in AutoLayoutView (created by AutoLayoutView)
    in AutoLayoutView (created by ScrollComponent)
    in RCTView (created by View)
    in View (created by ScrollComponent)
    in RCTView (created by View)
    in View (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by ScrollComponent)
    in ScrollComponent (created by ProgressiveListView)
    in ProgressiveListView (created by StickyContainer)
    in RCTView (created by View)
    in View (created by StickyContainer)
    in StickyContainer (created by FlashList)
    in FlashList (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in AwesomeProject(RootComponent)

**Comment by Prajwaltechversant** [comment]
steps to reproduce

1. create a new project  with react native
2. Set newArchEnabled=true in android/gradle.properties
3. install flashlist 
4. import and create list with flashlist
5. run the project, will get the error
6.

**Comment by jeroen-van-dijk** [comment]
Make sure you've ran `pod install` from the iOS folder:

https://github.com/react-native-linear-gradient/react-native-linear-gradient?tab=readme-ov-file#troubleshooting

**Comment by Prajwaltechversant** [comment]
No , i think issue is only if you enable the newArchitecture of react native

**Comment by WooMinGy** [comment]
I'm using 
`"react-native": "0.75.2",`
`"@shopify/flash-list": "1.7.1",`
`"react-native-reanimated": "3.15.1",`
among others. As I understand, FlashList has a dependency on Reanimated.

Even if you’re not using Reanimated directly, it might be worth installing it. If you do install Reanimated, don't forget to add 'react-native-reanimated/plugin' to the plugins section of your babel.config.js file!

In my case, I was able to resolve the issue by following these steps:

1. `rm -rf node_modules`
2. `rm pnpm-lock.yaml` (I ran this from the root in a monorepo setup. If you're not using a monorepo and using Yarn, remove the `yarn.lock` file instead)
3. `pnpm install` (or `yarn`)
4. `pnpm start --reset-cache` (to restart Metro)
5. `pnpm android` (to run the Android app)

**Comment by durango** [comment]
This issue persist even when `newArchitecture` is disabled. This solution may work for you:

1. `npm i react-native-reanimated react-native-screens react-native-safe-area-context`
2. `npx pod-install` (or `cd ios && pod install`)
3. `npm run ios`

There is most likely a version mismatch somewhere within the dependencies. Here are my versions:
```
    "react-native-reanimated": "^3.15.3",
    "react-native-safe-area-context": "^4.11.0",
    "react-native-screens": "^3.34.0",
```

If the above does not work for you, try installing `react-native-gesture-handler` then repeat steps 2 and 3.

**Comment by PedimallaRaju** [comment]
I am also facing the issue,  Can anyone give me the solution to this

**Comment by maukoese** [comment]
I've been struggling with this issue for the past one hour, I've realized removing the provider={PROVIDER_GOOGLE} prop the map works just fine, which is unfortunated cause the maps on iOS are not all that.

Hope this helps someone else.

**Comment by richkuo** [comment]
adding the prop `estimatedItemSize` with a valid value fixed it for me

**Comment by steveninety** [comment]
> Hopefully this will get looked at. The only workaround is disabling the new architecture...

Nevermind - even disabling newArchitecture and rebuilding does not solve the problem for me. It must be a combination of upgrades that I've made going from expo v51 to v52...

**Comment by mativecchio** [comment]
Solved with this https://github.com/surajitsarkar19/react-native-radial-gradient/issues/49#issuecomment-2376592946.

I hope it helps.

**Comment by abhishekvermax** [comment]
For me it was giving same error and I followed below step : (Assuming API is properly setup)

```
npx expo prebuild
npx react-native run-android 
```

After running these 2 commands i deleted Android and Ios folders and ran 

`npm start `

then selected "`development build`"

after that selected `android` and map showed up fine.

**Comment by GideonOdiokine** [comment]
Can someone help me with solution

**Comment by minhnc** [comment]
I also got same issue, tried all above suggestions but no luck

**Comment by NJneeraj** [comment]
Try Uninstalling the app..and then rebuild the project.Worked for me.

**Comment by IonutDaniel99** [comment]
Rollback to old React-Native (under 0.75.4) as the new 0.76 use a new architecture which most of libraries are not yet updated and it throws this problem.

**Comment by Monir-Shembesh** [comment]
Any Updates on this?

**Comment by OmarSaidIbrahim** [comment]
+1

**Comment by IonutDaniel99** [comment]
I figured out after several trial and error that this was also a problem from patches of different libraries.
In my case i had an error on React-Charts so i did a patch. That patch created the bubblingEventTypes because the return type was incorrect .

Might be worth looking if you have applied patches over node_modules libraries.

**Comment by mohanataraj** [comment]
Looks like the issue persists for me. Both on andriod and ios device build. weird

**Comment by EKoetsjarjan** [comment]
I had this issue and it was resolved by: 
- I removed my yarn workspaces nohoist property
- removed node-modules folders
- running yarn again
- restart metro
- pressing r for reload

not sure if it wil help for you

**Comment by OmarSaidIbrahim** [comment]
Ugh, I still get this issue only in development mode on my iPhone. 

iOS simulator works just fine. :(

**Comment by ballerolu** [comment]
+1

**Comment by Neon-jeff** [comment]
I fixed this error on ios by doing the following : 
1. removing node modules  - rm -rf node_modules
2. re-install packages - npm i
3. install expo v52 - npm i expo@^52
4. run a prebuild - npx expo prebuild --clear
5. I am using dev client on my send so - npx expo run:ios
6. ......wait for the next bug because of new Arch :)

**Comment by naqvitalha** [comment]
Folks, please upgrade to v2 if you're on new arch. I'll be closing this.
