### ISSUE TITLE
[V2][web] list crashes on window resize "Maximum update depth exceeded."!

### ISSUE THREAD

**Issue by a-eid** [Shopify/flash-list#1655]
## Current behavior

Flashlist v2 crashes on window resize on web. probably when numCol changes.

## Expected behavior

Flashlist should not crash and adapt accordingly 

## To Reproduce

- create a flashlist that adapts the numCols to the size of the window. 
- resize the window 

```tsx
export default function Screen() {
  const { width } = useWindowDimensions();

  const numColumns = React.useMemo(() => {
    if (width > 1000) return 4;
    if (width > 600) return 3;
    return 2;
  }, [width]);

  return (
    <FlashList
      key={numColumns}
      data={data}
      numColumns={numColumns}
      renderItem={({ item }) => (
        <View style={{ flex: 1, padding: 10, backgroundColor: '#eee', margin: 5 }}>
          <Text>{item.label}</Text>
        </View>
      )}
    />
  );
}
```

## Platform:

- [x] Web
- [ ] iOS
- [ ] Android

I have not tested this on android / ios yet.

## Environment
2.0.0-alpha.10

**Comment by naqvitalha** [comment]
I've found and fixed the issue. We'll ship the new alpha early next week. Thanks again for reporting this!

**Comment by naqvitalha** [comment]
This should be fixed in alpha.11.

**Comment by a-eid** [comment]
@naqvitalha I still can reproduce this on window resize. it's better than before for sure but still occurs.

**Comment by SamuraiF0x** [comment]
@naqvitalha Flashlist is causing my Next.js app to break entirely.

I'm seeing:
```tsx
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
React 4
RecyclerViewComponent webpack-internal:///(app-pages-browser)/../../node_modules/@shopify/flash-list/dist/recyclerview/RecyclerView.js:137
commitHookEffectListMount React
react-dom.development.js:26793

The above error occurred in the <NotFoundErrorBoundary> component:

RecyclerViewComponent@webpack-internal:///(app-pages-browser)/../../node_modules/@shopify/flash-list/dist/recyclerview/RecyclerView.js:32:22
```

**Comment by eth0izzle** [comment]
I can still replicate this issue by setting `numColumns` to `0`. Setting to `undefined` instead solves it but I feel `0` should be the same as `undefined` here. It doesn't happen in the native `FlatList`.

**Comment by naqvitalha** [comment]
@a-eid Can you provide me with a repro on expo snack? That will help me look into it quickly. I've reopened for now.

**Comment by naqvitalha** [comment]
This should be fixed in v2.0.2.
