### ISSUE TITLE
If dataSource is empty, an error will be reported stating 'index out of bounds, not enough layouts'

### ISSUE THREAD

**Issue by renyufei8023** [Shopify/flash-list#1707]
## Current behavior

I'm currently using version alpha.19-rc.3, and it throws an exception when the data is empty. However, if I switch to alpha.6, it works normally. Additionally, if I don't use a keyExtractor, it also behaves correctly without throwing any exceptions.

![Image](https://github.com/user-attachments/assets/c819cafd-2afb-48e2-bcc7-47ed2d389b71)

## Expected behavior

I hope to use keyExtractor without throwing exceptions when data is empty

## To Reproduce

<img width="1064" alt="Image" src="https://github.com/user-attachments/assets/5fa63bcd-79d1-4d73-8fb7-fbce414b04f5" />

## Platform:

- [ ] iOS

## Environment

[v2.0.0-alpha.19](https://github.com/Shopify/flash-list/releases/tag/v2.0.0-alpha.19)
[v2.0.0-rc.3](https://github.com/Shopify/flash-list/releases/tag/v2.0.0-rc.3)
alpha.19-rc.3

**Comment by renyufei8023** [comment]
If the data is empty and keyExtractor is set, this problem will occur

**Comment by naqvitalha** [comment]
It's fixed in rc.4. Thanks for reporting this!

**Comment by FightFarewellFearless** [comment]
> It's fixed in rc.4. Thanks for reporting this!

This error still occurs when using a full-height ListHeaderComponent and scrolling to the bottom as quickly as possible, before the first item has rendered. The error then appears

**Comment by naqvitalha** [comment]
@FightFarewellFearless Can you open a new issues and include a repro please? It can be on expo snack
