### ISSUE TITLE
Expo error: requireNativeComponent: "AutoLayoutView" was not found in the UIManager

### ISSUE THREAD

**Issue by MaximFedarau** [Shopify/flash-list#565]
## Current behavior

When I am trying to use `<FlashList />` component, then I have errors.
![Simulator Screen Shot - iPhone 13 - 2022-08-16 at 12 25 59](https://user-images.githubusercontent.com/87207122/184846043-ae2d3e0f-1a22-41b7-9007-72aae1b8e1b6.png)
![Simulator Screen Shot - iPhone 13 - 2022-08-16 at 12 26 18](https://user-images.githubusercontent.com/87207122/184846159-06c532c4-768e-45e8-9268-eaa4210abd77.png)
![Simulator Screen Shot - iPhone 13 - 2022-08-16 at 12 26 22](https://user-images.githubusercontent.com/87207122/184846168-2e6a7020-ad58-4685-ab0f-e79770452522.png)

## Expected behavior

I wan to render `<FlashList />` component.

## Platform:

- [x] iOS
- [x] Android

## Environment

node - 18.7.0
expo - 45.0.0
flash-list - 1.2.1
jsEngine - `hermes` (but this does not work on `jsc` either)

**Comment by MaximFedarau** [comment]
Fixed this problem.
I just run `expo upgrade`.

**Comment by alexreyes** [comment]
Still getting this bug with the bare expo workflow. I only get it when running my app on my device with `npm run ios`. It seems to work fine on the simulator

**Comment by MaximFedarau** [comment]
> Still getting this bug with the bare expo workflow. I only get it when running my app on my device with `npm run ios`. It seems to work fine on the simulator

1. Delete `node_modules` and `yarn.lock` or `package-lock.json`. Then run `yarn install` (or just simple `yarn`) or `npm install`.
If this does not work:
2. Update your ExpoCLI + Try to create empty bare workflow project and install flash-list package. If everything will work fine, then try to find out and fix the differences.
